[package]
name = "huginn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = "1.0.8"
flume = "0.10.9"
futures = "0.3.17"
gtk = "0.14"
url = "2.2.2"
